#!/bin/csh -f
setenv XERCESCROOT /users/gwl/programs/xerces-c-src2_4_0

if !($?LD_LIBRARY_PATH) then
    setenv LD_LIBRARY_PATH $XERCESCROOT/lib
else
    setenv LD_LIBRARY_PATH $XERCESCROOT/lib:$LD_LIBRARY_PATH
endif

./ResolutionServer $*
