#!/bin/csh

set FILE = ""
if ( $#argv == 1 ) then
  if ( "`echo $0|cut -c1`" == "/" ) then
    set FILE = "$0"
  else
    set FILE = "`pwd`/${0}"
  endif
endif

ssh squall.astro.washington.edu "cd ~gwl/public/ResolutionServer-0.2-alpha; ./run_server.sh +p4 $FILE" |tail -1 | xargs java -jar Salsa.jar
ssh squall.astro.washington.edu pkill charmrun
