#!/bin/csh

set REMOTEHOST = squall.astro.washington.edu
set REMOTEDIR = /users/gwl/public/ResolutionServer-0.2-beta

set FILE = ""
if ( $#argv == 1 ) then
  if ( "`echo $1|cut -c1`" == "/" ) then
    set FILE = "$1"
  else
    set FILE = "`pwd`/${1}"
  endif
endif

set SALSAARGS = `ssh $REMOTEHOST "cd $REMOTEDIR; ./run_server.sh +p4 $FILE" |tail -1`
set SALSAARGS = "$SALSAARGS $FILE"
java -jar Salsa.jar $SALSAARGS
ssh $REMOTEHOST pkill charmrun
